apiVersion: skaffold/v3
kind: Config
manifests:
 rawYaml:
 - ./infra/k8s/*
deploy:
 kubectl: {}
build:
  local:
    push: true
  # googleCloudBuild:
  #   projectId: ticketing-dev-325321
  artifacts:
    - image: yonatanlavie/auth
    # - image: us.gcr.io/ticketing-dev-325321/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .                                    
    - image: yonatanlavie/client
    # - image: us.gcr.io/ticketing-dev-325321/auth
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .                                    
    - image: yonatanlavie/tickets
    # - image: us.gcr.io/ticketing-dev-325321/auth
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .                                    
    - image: yonatanlavie/orders
    # - image: us.gcr.io/ticketing-dev-325321/auth
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .  
    - image: yonatanlavie/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .                                  
    - image: yonatanlavie/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .                                  