apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: yonatanlavie/auth
        env:
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_KEY
          - name: GOOGLE_CLIENT_ID
            value: "128187419836-v03cevjufhfbadbo8ih88j0mohjnplni.apps.googleusercontent.com"
          - name: GOOGLE_CLIENT_SECRET
            value: "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"
          - name: FACEBOOK_CLIENT_ID
            value: "988466155477585"
          - name: FACEBOOK_CLIENT_SECRET
            value: "36f2abc435ba7be2342042a5c754e6bc"
          - name: MONGO_URI
            value: "mongodb://auth-mongo-srv:27017/auth"
        # image: us.gcr.io/ticketing-dev-325321/auth
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000