apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
spec:
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - name: nats
        image: nats-streaming
        args:
          [
            "-p",
            "4222",
            "-m",
            "8222",
            "-hbi", # sends hart bit every 5s to the client
            "5s",
            "-hbt", # how long can client can respond to server
            "5s",
            "-hbf", # how meny times can client fills respond back hart bit to nats server before the server delete him from subscription
            "2",
            "-SD",
            "-cid",
            "ticketing",
          ]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: nats-srv
spec:
  selector:
    app: nats
  ports:
  - name: client
    protocol: TCP
    port: 4222
    targetPort: 4222
  - name: monitoring
    protocol: TCP
    port: 8222
    targetPort: 8222
