apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
type: Opaque
stringData :
  STRIPE_KEY: 'sk_test_51Jztk9KcI4o352TQLx2j8hJZj4t5qBhG9faFzLP5jzhlKRcnetTK8yUC0cKo4XjAy8G7MdDtIbdsjmb0zVOHrWuf00gTFUerOT'
